config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  get "artists" => "artists#index"
  get 'artists/new' => "artists#new", as: :new_artist
  get "artists/:id" => "artists#show", as: :artist

  post "artists" => "artists#create"
  delete "artists/:id" => "artists#destroy"

  get "songs" =>"songs#index"
  get 'songs/new' => "songs#new", as: :new_song
  get "songs/:id" => "songs#show", as: :song

  post "songs" => "songs#create"
  delete "songs/:id" => "songs#destroy"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  
  validates :name, presence: true
  validates :song, presence: true
  validates :name, uniqueness: true


  def self.order_by_name
    order(:name)
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  def self.order_by_name
    order(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
      @artists = Artist.all
    end

    def new
      @artist = Artist.new
    end

    def show
      @artist = Artist.find(params[:id])
    end

    def create
      artist_params = params.require(:artist).permit(:name, :song)

      @artist = Artist.new(artist_params)

      if @artist.save
         redirect_to @artist
      else
         render 'new'
      end
    end

    def destroy
      @artist = artist.find(params[:id])

      @artist.destroy

      redirect_to artists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @song = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    song_params = params.require(:song).permit(:artist_name, :name_song, :duration, :genre)

    @song = Song.new(song_params)

    if @song.save
       redirect_to @song
    else
       render 'new'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
    <p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>
<br>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :song %>
  <%= f.text_field :song %>

  <%= f.submit "Create" %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<p>Song: <%= @artist.song %></p>


<%= link_to "[Delete]", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify Nieuw</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br><br>
    <hr>

    <%= link_to "[All artists]", root_path %>
    <%= link_to "[New song]", new_song_path %>
    <%= link_to "[New artist]", new_artist_path %>

  </body>
</html>

app/views/songs/index.html.erb
<h1>songs</h1>

<% @song.each do |song| %>
    <p><%= link_to song.name_song, song_path(song.id) %></p>
<% end %>

app/views/songs/new.html.erb
<!-- app/views/songs/new.html.erb -->

<h1>New song</h1>

<%= form_for @song do |f| %>
  <%= f.label :artist_name  %>
  <%= f.text_field :artist_name  %>

  <%= f.label :name_song %>
  <%= f.text_field :name_song %>

  <%= f.label :duration %>
  <%= f.number_field :duration %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.submit "Create" %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.artist_name %></h1>

<p>Title song:<%= @song.name_song %>
<p>Duration: <%= @song.duration %></p>
<p>Genre: <%= @song.genre %></p>

<%= link_to "[Delete]", song_path(@song.id), method: :delete, data: { confirm: "Really?" } %>